### ISSUE TITLE
Eth explorer

### ISSUE THREAD

**Issue by kyriediculous** [javahippie/geth-dev#28]
A full etherscan implementation would be nice, but a lightweight one like https://github.com/etherparty/explorer/tree/master/app would do fine I guess.

The thing is, the monitor is nice but it mostly only works for PoW. 

Currently looking into it, I'll submit a PR once completed.

**Comment by kyriediculous** [comment]
```
  geth-explorer:
    hostname: geth-explorer
    depends_on:
      - geth-dev-miner-1
    ports:
      - 8080:8080
    build:
      context: ./explorer
    container_name: geth-explorer
    networks:
      chainnet:
        ipv4_address: 172.25.0.125
```

```
FROM node:6.11-alpine

WORKDIR "/opt"

RUN apk add --update git && \
    git clone https://github.com/kyriediculous/Ethereum-Block-Explorer.git

WORKDIR "/opt/Ethereum-Block-Explorer"

RUN npm install

CMD npm run start

EXPOSE 8080
```
